### PR TITLE
Terminal Fixes

### PR DESCRIPTION
**Pull request by biakp**
Terminal fixes ☕

### CODE REVIEW

**Comment by biakp** [comment]
@patrickelectric can you check it please? 😸

**Comment by patrickelectric** [comment]
Hi @biakp, thansk for the update, but there is a couple of problems:
- The terminal widget has two vertical scrollbars.
image
image

- When you resize the terminal a couple of times, the canvas goes up.
image  

- When you hide the terminal it's impossible to get it back
- There is a weird gray area effect when it's resized
terminal_scroll

**Comment by biakp** [comment]
@patrickelectric  Fixed those bugs and a few more 🐛 🐞

**Comment by patrickelectric** [comment]
Thanks @biakp,  looks good!

**Pull request merged**
