### PR TITLE
Status Bar

### PR DESCRIPTION
**Pull request by biakp**
About the splitter height.... now it is 50px + status bar :)

### CODE REVIEW

**Comment by patrickelectric** [comment]
Thanks for the PR @biakp !
There is just a small thing, sorry if I was not clear in my previous explanation, but the idea of the status bar is to be only under the code editor and not for both editor and canvas.
That's what I have in mind:
image
Probably it'll baster for you than for me to fix that :)

Let me know if something was not clear

**Comment by biakp** [comment]
> Thanks for the PR @biakp !
> There is just a small thing, sorry if I was not clear in my previous explanation, but the idea of the status bar is be only under the code editor and both for both editor and canvas.
> That's what I have in mind:
> image
> Probably it'll baster for you than for me to fix that :)
> 
> Let me know if something was not clear

No problem! Will fix it asap 🚀

**Comment by biakp** [comment]
@patrickelectric can you check it now? 😸

**Comment by patrickelectric** [comment]
Yes, that's it, thanks!

**Pull request merged**
